
server:
  port: "9004"
  read_timeout: 60 # in seconds
  write_timeout: 60 # in seconds
  log_level: 4 # Num 4 is INFO level


token:
  jwt_secret: $3cr3t
  one_day_in_seconds: 86400
  access_tokenTTL: 15 # 15 days
  refresh_tokenTTL: 30 # 30 days